In [ ]:
x = 7
y = "data"

print(x)
print(y)

my_variable = 10
print(my_variable)

my_variable += 5 #this does my_variable = my_variable + 5
print(my_variable)





7
data
10
15


Working with strings

In [11]:
"I am an MSBA student"

question = "What are you studying?"
answer = "Analytics!"

print(question)
print(answer)

print(question + " " + answer) #Concatentation using standard format and adds forced space 
print(f"{question} {answer}") #Concatentation using f-string format 

###adding a line break 
print(question + "\n" + answer)

type(answer)


What are you studying?
Analytics!
What are you studying? Analytics!
What are you studying? Analytics!
What are you studying?
Analytics!


str

In [ ]:
len(answer) #since not saved to variable will be overriden 
#if running something else so moved to new code segment 

10

In [16]:
### Indexing a string 

answer[0] #First character 
answer[2] #Third character
answer[9] #Tenth character

answer[-1] #Last character

'!'

In [ ]:
course = 'CTBA'

len(course)

print(course[0:2]) #First two characters (not include last index number 2)



CT


In [ ]:
#Functions and Methods 
#built-in functions like input or print 
#method would be .upper or .lower etc 

answer_cap = answer.upper() #Convert to uppercase
print(answer_cap)

answer.lower() #Convert to lowercase 

answer.find("t") #Find the index of the first occurence of "t"

ANALYTICS!


5

In [26]:
name = "Julia Levy"

print("Hello, my name is " + name + ". I am studying Business Analytics.")
print(f"Hello, my name is {name}. I am studying Business Analytics.")

Hello, my name is Julia Levy. I am studying Business Analytics.
Hello, my name is Julia Levy. I am studying Business Analytics.


In [ ]:
##Tuples 
t1 = (1,2,3,4,5)
print(t1)

#t1[0] = 11 #Tuples are immutable, so this will give an error
#Tuples usually used in dictionaries if want fixed set of values,
#read-only data sets, or as a key in a dictionary 

(1, 2, 3, 4, 5)


In [ ]:
###Dictionaries 
d1 = {"name": "Julia Levy", "age": 22, "city": "Williamsburg"}
print(d1)
print(d1["name"]) #make sure key is in quotes if it is a string 
#and because indexing by looking at text 

d1["email"] = "jdlevy@wm.edu"
print(d1)


{'name': 'Julia Levy', 'age': 22, 'city': 'Williamsburg'}
Julia Levy
{'name': 'Julia Levy', 'age': 22, 'city': 'Williamsburg', 'email': 'jdlevy@wm.edu'}


In [ ]:
##formatting the dictionary output with a for loop

for key,value in d1.items(): #items returns a key,value pair 
    print(key, ":", value) #could use f-string format too (use commas not addition)
    


name : Julia Levy
age : 22
city : Williamsburg
email : jdlevy@wm.edu


In [38]:
##Dictionary of Dictionaries
#outer dictionary and inner dictionary 

people = {
    "person 1": {"name": "Julia Levy", "age": 22, "city": "Williamsburg"},
    "person 2": {"name": "MV Nye", "age": 23, "city": "NYC"}
}

print(people)

{'person 1': {'name': 'Julia Levy', 'age': 22, 'city': 'Williamsburg'}, 'person 2': {'name': 'MV Nye', 'age': 23, 'city': 'NYC'}}


In [41]:
distances = {
    "A":{"B": 10, "C": 15}, 
    "B":{"A": 10, "C": 20},
    "C":{"A": 15, "B": 20}
}

print(distances)

{'A': {'B': 10, 'C': 15}, 'B': {'A': 10, 'C': 20}, 'C': {'A': 15, 'B': 20}}


In [51]:
student_gpa = {
    "Bryce":3.8,"Mann":3.6,"Tai":3.4
}
print(student_gpa)

students = {
    "student 1": {"name": "Bryce", "major": "Business Analytics", "gpa":3.8, "courses": 4},
    "student 2": {"name": "Mann", "major": "Business Analytics", "gpa":3.6, "courses": 4},
    "student 3": {"name": "Tai", "major": "Business Analytics", "gpa":4.0, "courses": 4}
}
students["student 4"] = {"name": "Conner", "major": "Business Analytics", "gpa":4.0, "courses": 4}
print(students)

{'Bryce': 3.8, 'Mann': 3.6, 'Tai': 3.4}
{'student 1': {'name': 'Bryce', 'major': 'Business Analytics', 'gpa': 3.8, 'courses': 4}, 'student 2': {'name': 'Mann', 'major': 'Business Analytics', 'gpa': 3.6, 'courses': 4}, 'student 3': {'name': 'Tai', 'major': 'Business Analytics', 'gpa': 4.0, 'courses': 4}, 'student 4': {'name': 'Conner', 'major': 'Business Analytics', 'gpa': 4.0, 'courses': 4}}


In [56]:
###If Statements 
x = 10 
if x > 5: 
    print("x is greater than 5")

##If Else Statements 
x = 4
if x % 2 == 0: 
    print("x is even")
else: #note indentation
    print("x is odd")
    
##Working with Elif 
x = 0 
if x > 0: 
    print("x is positive")
elif x == 0: 
    print("x is zero")
else: 
    print("x is negative")    

x is greater than 5
x is even
x is zero


In [ ]:
###for loops with an i and a range function
for i in range(5): 
    print("i is ", i)
#iterates over every item of the range 

i is  0
i is  1
i is  2
i is  3
i is  4


In [ ]:
###while loop with if statement 
x = 0 

while x<5: 
    if x % 2 == 0: 
        print(x, "is even")
    else: 
        print(x, "is odd")
    x += 1 #same thing as count 
    


0 is even
1 is odd
2 is even
3 is odd
4 is even


Using NumPy to create arrays

In [74]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)

list2 = [(1,2,3), (4,5,6)]
print(list2)

arr2 = np.array([(1,2,3),(4,5,6)])
print(arr2)

list = [1,2,3]
arr1 = np.array([1,2,3])
for e in list: 
    print(e)
for e in arr1: 
    print(e)

#adding to an array
arr1 = np.append(arr1, 4)
arr1 = np.append(arr1, [5])
for e in arr1: 
    print(e)

#add two arrays 
arr2 = arr1 + arr1 
for e in arr2: 
    print(e)

[1 2 3 4 5]
[(1, 2, 3), (4, 5, 6)]
[[1 2 3]
 [4 5 6]]
1
2
3
1
2
3
1
2
3
4
5
2
4
6
8
10
